version: '3.8'
services:
backend:
build:
context: ./amsrest2024
dockerfile: Dockerfile
ports:
 "8080:8080"

environment:
  SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/amsrestdbdb

  SPRING_DATASOURCE_USERNAME=root

  SPRING_DATASOURCE_PASSWORD=password

depends_on:
 db


frontend:
build:
context: ./amsfront2024
dockerfile: Dockerfile
ports:
 "4200:80"


db:
image: mysql:5.7
ports:
  "3306:3306"

environment:
  MYSQL_DATABASE=amsrestdb

  MYSQL_USER=user

  MYSQL_PASSWORD=password

volumes:
  db-data:/var/lib/mysql


volumes:

db-data: